version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - apiaspnet
      - db
      - minio

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
      - apiaspnet
      - minio

  apiaspnet:
    build:
      context: ./apiaspnet
      dockerfile: Dockerfile
    container_name: apiaspnet
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=automatisation;User=root;Password=automatisation;
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__BucketName=syracuse
    depends_on:
      - db
      - minio

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: automatisation
      MYSQL_DATABASE: automatisation
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - '8900:8900'
    volumes:
      - 'minio:/data/minio'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: 'minio server /data/minio --console-address ":8900"'

volumes:
  db-data:
  minio:
    driver: local